version: "3.8"
services:
  flask-app:
    image: naw55/flask-app
    build: ./flask-app
    container_name: flask-app
    
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment: 
       DATABASE_URI: "mysql+pymysql://root:password123@mysql:3306/flask-db"
  mysql:
    image: mysql:latest
    container_name: mysql
    build: ./db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: flask-app
      target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:  password123
      MYSQL_DATABASE: flask-db
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
volumes:
  flask-app: